- id: "/"
  title: "AEEF - Asociación Juvenil Española de Estudiantes de Física"
  description: "La Asociación Juvenil Española de Estudiantes de Física (AEEF) es una organización sin ánimo de lucro que busca reunir a todos los estudiantes de física de España. AEEF es el Comité Nacional Español de la Asociación Internacional de Estudiantes de Física (IAPS)."
  keywords: "aeef asociación juvenil española de estudiantes de física iaps"
- id: "/eventi/"
  title: "AEEF - Eventos"
  description: "AEEF organiza eventos de carácter local, nacional e internacional para sus miembros, como conferencias, visitas a laboratorios o charlas de estudiantes, investigadores y profesores."
  keywords: "aeef eventos conferencia icps plancks iaps"
